/**
 * Seed data for compliance logs — transcribed verbatim from the design
 * prototype's `OpsDB.logs` (Ops.jsx).
 */
import type { LogEntry } from '@/features/ops-logs/application/store/logs.types';

export const OPS_LOGS: readonly LogEntry[] = [
  {
    id: 1,
    action: 'Hospital suspended — Nirmal Ortho & Spine',
    actor: 'riya.sharma@medibook.in',
    module: 'Hospitals',
    ip: '10.42.8.11',
    time: 'June 13, 2026 · 09:42',
    sev: 'Critical',
  },
  {
    id: 2,
    action: 'Settlement released — ₹ 1,28,250',
    actor: 'riya.sharma@medibook.in',
    module: 'Settlements',
    ip: '10.42.8.11',
    time: 'June 12, 2026 · 17:05',
    sev: 'Info',
  },
  {
    id: 3,
    action: 'Role permissions changed — Finance Admin',
    actor: 'anil.kapoor@medibook.in',
    module: 'Users & Roles',
    ip: '10.42.8.14',
    time: 'June 12, 2026 · 15:31',
    sev: 'Critical',
  },
  {
    id: 4,
    action: 'Failed login attempt (3x)',
    actor: 'unknown@23.94.61.2',
    module: 'Auth',
    ip: '23.94.61.2',
    time: 'June 12, 2026 · 11:18',
    sev: 'Warning',
  },
  {
    id: 5,
    action: 'Invoice regenerated — INV-2026-0234',
    actor: 'meera.pillai@medibook.in',
    module: 'Billing',
    ip: '10.42.8.19',
    time: 'June 11, 2026 · 16:47',
    sev: 'Info',
  },
  {
    id: 6,
    action: 'Platform user deleted — dev.trivedi@gmail.com',
    actor: 'anil.kapoor@medibook.in',
    module: 'Platform Users',
    ip: '10.42.8.14',
    time: 'June 11, 2026 · 12:03',
    sev: 'Critical',
  },
  {
    id: 7,
    action: 'Data export — bookings FY 2025-26',
    actor: 'meera.pillai@medibook.in',
    module: 'Reports',
    ip: '10.42.8.19',
    time: 'June 10, 2026 · 18:22',
    sev: 'Warning',
  },
  {
    id: 8,
    action: 'Media purged — 214 orphaned files',
    actor: 'system@medibook.in',
    module: 'Media',
    ip: '10.42.0.1',
    time: 'June 10, 2026 · 02:00',
    sev: 'Warning',
  },
  {
    id: 9,
    action: 'API key rotated — payments gateway',
    actor: 'riya.sharma@medibook.in',
    module: 'Settings',
    ip: '10.42.8.11',
    time: 'June 09, 2026 · 10:40',
    sev: 'Info',
  },
  {
    id: 10,
    action: 'Settings updated — payout schedule',
    actor: 'riya.sharma@medibook.in',
    module: 'Settings',
    ip: '10.42.8.11',
    time: 'June 08, 2026 · 09:12',
    sev: 'Info',
  },
];
