/**
 * Seed data for platform users (patient accounts) — transcribed verbatim from
 * the design prototype's `OpsDB.platformUsers` (Ops.jsx). Avatar paths point
 * at `public/assets`.
 */
import type { PlatformUser } from '@/features/ops-platform-users/application/store/platformUsers.types';

export const PLATFORM_USERS: readonly PlatformUser[] = [
  {
    id: 1,
    name: 'Aarav Mehta',
    email: 'aarav.mehta@gmail.com',
    phone: '+91 98111 20415',
    city: 'Mumbai',
    bookings: 12,
    joined: 'January 12, 2026',
    status: 'Active',
    av: '/assets/avatar-2.jpg',
    family: [
      { name: 'Rhea Mehta', rel: 'Spouse', age: 31, gender: 'Female' },
      { name: 'Kabir Mehta', rel: 'Son', age: 6, gender: 'Male' },
      { name: 'Suresh Mehta', rel: 'Father', age: 64, gender: 'Male' },
    ],
    history: [
      {
        hospital: 'Meridian City Hospital',
        department: 'Cardiology',
        date: 'June 14, 2026',
        status: 'Scheduled',
      },
      {
        hospital: 'Kaveri General Hospital',
        department: 'General Medicine',
        date: 'April 02, 2026',
        status: 'Completed',
      },
      {
        hospital: 'Meridian City Hospital',
        department: 'Paediatrics',
        date: 'March 21, 2026',
        status: 'Completed',
      },
    ],
  },
  {
    id: 2,
    name: 'Sana Qureshi',
    email: 'sana.q@gmail.com',
    phone: '+91 99870 33261',
    city: 'Hyderabad',
    bookings: 8,
    joined: 'January 28, 2026',
    status: 'Active',
    av: '/assets/avatar-3.jpg',
    family: [{ name: 'Imran Qureshi', rel: 'Spouse', age: 36, gender: 'Male' }],
    history: [
      {
        hospital: 'Vasudha Medical Centre',
        department: 'Gynaecology',
        date: 'April 11, 2026',
        status: 'Completed',
      },
      {
        hospital: 'Vasudha Medical Centre',
        department: 'ENT',
        date: 'March 08, 2026',
        status: 'No-show',
      },
    ],
  },
  {
    id: 3,
    name: 'Vikram Rao',
    email: 'vikram.rao@outlook.com',
    phone: '+91 98450 71923',
    city: 'Bengaluru',
    bookings: 21,
    joined: 'February 03, 2026',
    status: 'Active',
    av: '/assets/avatar-4.jpg',
    family: [
      { name: 'Lakshmi Rao', rel: 'Mother', age: 68, gender: 'Female' },
      { name: 'Anika Rao', rel: 'Daughter', age: 9, gender: 'Female' },
    ],
    history: [
      {
        hospital: 'Trinity Care & Research',
        department: 'Orthopaedics',
        date: 'June 13, 2026',
        status: 'In Queue',
      },
      {
        hospital: 'Trinity Care & Research',
        department: 'Orthopaedics',
        date: 'March 30, 2026',
        status: 'Completed',
      },
      {
        hospital: 'Padma Eye Foundation',
        department: 'Ophthalmology',
        date: 'March 12, 2026',
        status: 'Completed',
      },
    ],
  },
  {
    id: 4,
    name: 'Meera Nair',
    email: 'meera.nair@gmail.com',
    phone: '+91 98470 55810',
    city: 'Kochi',
    bookings: 5,
    joined: 'February 17, 2026',
    status: 'Blocked',
    av: null,
    family: [],
    history: [
      {
        hospital: "Ashwini Children's Care",
        department: 'Paediatrics',
        date: 'February 20, 2026',
        status: 'Cancelled',
      },
    ],
  },
  {
    id: 5,
    name: 'Rohit Bansal',
    email: 'rohit.b91@gmail.com',
    phone: '+91 98100 42376',
    city: 'Delhi',
    bookings: 14,
    joined: 'February 25, 2026',
    status: 'Active',
    av: '/assets/avatar-2.jpg',
    family: [{ name: 'Nidhi Bansal', rel: 'Spouse', age: 33, gender: 'Female' }],
    history: [
      {
        hospital: 'Sunrise Multispeciality',
        department: 'ENT',
        date: 'June 11, 2026',
        status: 'Cancelled',
      },
      {
        hospital: 'Sunrise Multispeciality',
        department: 'General Medicine',
        date: 'April 03, 2026',
        status: 'Completed',
      },
    ],
  },
  {
    id: 6,
    name: 'Ananya Iyer',
    email: 'ananya.iyer@gmail.com',
    phone: '+91 99400 18734',
    city: 'Chennai',
    bookings: 9,
    joined: 'March 06, 2026',
    status: 'Active',
    av: '/assets/avatar-3.jpg',
    family: [],
    history: [
      {
        hospital: 'Lotus Heart Institute',
        department: 'Cardiology',
        date: 'April 10, 2026',
        status: 'Completed',
      },
    ],
  },
  {
    id: 7,
    name: 'Farhan Sheikh',
    email: 'farhan.sk@gmail.com',
    phone: '+91 98920 60148',
    city: 'Pune',
    bookings: 3,
    joined: 'March 19, 2026',
    status: 'Blocked',
    av: null,
    family: [{ name: 'Zoya Sheikh', rel: 'Daughter', age: 4, gender: 'Female' }],
    history: [
      {
        hospital: 'Sunrise Multispeciality',
        department: 'Paediatrics',
        date: 'March 19, 2026',
        status: 'No-show',
      },
    ],
  },
  {
    id: 8,
    name: 'Divya Kulkarni',
    email: 'divya.k@gmail.com',
    phone: '+91 98600 27459',
    city: 'Nagpur',
    bookings: 17,
    joined: 'April 01, 2026',
    status: 'Active',
    av: '/assets/avatar-4.jpg',
    family: [
      { name: 'Prakash Kulkarni', rel: 'Father', age: 61, gender: 'Male' },
      { name: 'Meena Kulkarni', rel: 'Mother', age: 58, gender: 'Female' },
    ],
    history: [
      {
        hospital: 'Nirmal Ortho & Spine',
        department: 'Orthopaedics',
        date: 'June 14, 2026',
        status: 'Scheduled',
      },
      {
        hospital: 'Nirmal Ortho & Spine',
        department: 'Orthopaedics',
        date: 'March 28, 2026',
        status: 'Completed',
      },
    ],
  },
];
