/**
 * Seed patient records — the list the design prototype's `initStore()`
 * derives from the seed appointments, materialized as literals:
 * - one patient per unique MRN, in first-appointment order (all 12 seed
 *   MRNs are unique, so the order matches the appointment seed 1:1);
 * - email = name lowercased, non-letters collapsed to "." + "@mail.com";
 * - address = AREAS[appointment index % 6] + ", Bengaluru" with
 *   AREAS = [Indiranagar, Koramangala, Jayanagar, Whitefield, HSR Layout,
 *   Malleshwaram].
 */

import type { Patient } from './patients.types';

export const SEED_PATIENTS: readonly Patient[] = [
  {
    mrn: 'AP847201',
    name: 'Ellen Kinderson',
    age: 32,
    gender: 'Female',
    phone: '9876543210',
    email: 'ellen.kinderson@mail.com',
    address: 'Indiranagar, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847202',
    name: 'John Miller',
    age: 45,
    gender: 'Male',
    phone: '9876543211',
    email: 'john.miller@mail.com',
    address: 'Koramangala, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847203',
    name: 'Maya Rao',
    age: 29,
    gender: 'Female',
    phone: '9876543212',
    email: 'maya.rao@mail.com',
    address: 'Jayanagar, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847204',
    name: 'Arun Patel',
    age: 51,
    gender: 'Male',
    phone: '9876543213',
    email: 'arun.patel@mail.com',
    address: 'Whitefield, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847205',
    name: 'Sara Iqbal',
    age: 38,
    gender: 'Female',
    phone: '9876543214',
    email: 'sara.iqbal@mail.com',
    address: 'HSR Layout, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847206',
    name: 'Vikram Das',
    age: 60,
    gender: 'Male',
    phone: '9876543215',
    email: 'vikram.das@mail.com',
    address: 'Malleshwaram, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847207',
    name: 'Nisha Roy',
    age: 24,
    gender: 'Female',
    phone: '9876543216',
    email: 'nisha.roy@mail.com',
    address: 'Indiranagar, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847208',
    name: 'Imran Sheikh',
    age: 41,
    gender: 'Male',
    phone: '9876543217',
    email: 'imran.sheikh@mail.com',
    address: 'Koramangala, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847209',
    name: 'Priya Nair',
    age: 35,
    gender: 'Female',
    phone: '9876543218',
    email: 'priya.nair@mail.com',
    address: 'Jayanagar, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847210',
    name: 'George Thomas',
    age: 58,
    gender: 'Male',
    phone: '9876543219',
    email: 'george.thomas@mail.com',
    address: 'Whitefield, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847211',
    name: 'Fatima Begum',
    age: 27,
    gender: 'Female',
    phone: '9876543220',
    email: 'fatima.begum@mail.com',
    address: 'HSR Layout, Bengaluru',
    status: 'Active',
  },
  {
    mrn: 'AP847212',
    name: 'Daniel Joseph',
    age: 49,
    gender: 'Male',
    phone: '9876543221',
    email: 'daniel.joseph@mail.com',
    address: 'Malleshwaram, Bengaluru',
    status: 'Active',
  },
];
